package com.mentorly.session.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for secure join session response.
 * This DTO is ONLY returned after the backend has verified that the user is
 * authorized to join.
 * It includes the meeting link that was generated by the Google Calendar API.
 */
/**
 * Encapsulates secure join session response.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SecureJoinSessionResponse {

    private Long sessionId;

    private String sessionTitle;

    // The meeting link is ONLY exposed after authorization verification
    private String meetingLink;

    // Status indicators
    private boolean allowed;

    private String message;

    // Join window information
    private boolean withinJoinWindow;

    private long minutesUntilStart;

    private long minutesUntilEnd;
}
